#!/usr/bin/env node
process.env.DEBUG = process.env.DEBUG || "*"
global.configPath = '/etc/autodocker/config.js'
require('./init').init()

const R             = require('ramda')
const {spawn, exec} = require('./process')
const ip            = require("ip")
const fs            = require('fs')
const config        = require('./config')
const debug         = R.memoize(require('debug'))

const tick = () => {
  const localIp = ip.address()
  const imageToDnsmasq = R.map(image => `address=/${image}/${localIp}`)
  const runningHosts = R.pluck(0, JSON.parse(fs.readFileSync(config.rulesFile)))
  const newConf = imageToDnsmasq(runningHosts).join('\n')
  const oldConf = fs.readFileSync(config.dnsmasqConf, 'utf8')
  
  if (newConf != oldConf) {
    fs.writeFileSync(config.dnsmasqConf, newConf)
    debug('dnsmasq')("\n"+newConf+"\n")
    exec('pkill dnsmasq; dnsmasq')
    debug('dnsmasq')('reloaded')
  }
}

tick()
setInterval(tick, 1000)
