#!/usr/bin/env node
process.env.DEBUG = process.env.DEBUG || "*"
global.configPath = '/etc/autodocker/config.js'

const R             = require('ramda')
const {spawn, exec} = require('./process')
const ip            = require("ip")
const fs            = require('fs')
const config        = require('./config')
const hook          = require('./hook')
const proxyRules    = require('./proxyRules')

const localIp = ip.address()
const imageToDnsmasq = R.map(image => `address=/${image}/${localIp}`)
const runningHosts = () => R.pluck(0, proxyRules.get())

const tick = () => {
  const newConf = imageToDnsmasq(runningHosts()).join('\n')
  const oldConf = fs.readFileSync(config.dnsmasqConf, 'utf8')
  
  if (newConf != oldConf) {
    fs.writeFileSync(config.dnsmasqConf, newConf)
    hook('dnsmasq:reload')(newConf)
    exec('pkill dnsmasq; dnsmasq')
  }
}

setInterval(tick, 1000)
